# Generated by Django 4.0.3 on 2022-03-30 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column_Tab',
            fields=[
                ('column_id', models.IntegerField(primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Executor_Tab',
            fields=[
                ('executor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('second_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Tab',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('card_date', models.DateField()),
                ('column_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.column_tab')),
                ('executor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.executor_tab')),
            ],
        ),
    ]
