# Generated by Django 4.0.3 on 2022-03-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column_tab',
            name='cards',
            field=models.ManyToManyField(related_name='card_tab_name', to='kanban.card_tab', verbose_name='card_tab'),
        ),
    ]
