# Generated by Django 4.0.3 on 2022-03-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_column_tab_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_tab',
            name='fio',
            field=models.ManyToManyField(related_name='executor_tab_name', to='kanban.executor_tab', verbose_name='executor_tab'),
        ),
    ]
